from sqlalchemy import Column, String, Boolean, DateTime, ForeignKey, Float, JSON, func
from sqlalchemy.dialects.postgresql import UUID
import uuid
from .base import Base

class Evidence(Base):
    """
    Tracks visual/documentary evidence tied to a Claim, and stores the isolated pipeline scores.
    """
    __tablename__ = 'evidence'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    claim_id = Column(UUID(as_uuid=True), ForeignKey('claims.id'), nullable=False)
    
    evidence_type = Column(String(50), nullable=False) # 'camera_video' (Pipeline A) or 'document' (Pipeline B)
    file_url = Column(String(500), nullable=False) # S3/MinIO bucket path
    
    # Pipeline A (CV Layer) Specifics
    passed_physical_challenge = Column(Boolean, default=False)
    cv_layer_scores = Column(JSON) # {"hands": 0.9, "product_match": 0.95, "damage": 0.8}
    
    # General Scoring
    authenticity_score = Column(Float) # The isolated score generated by the pipeline
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
